//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numberskills.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Numberskills.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to användande.
        /// </summary>
        public static string _using {
            get {
                return ResourceManager.GetString("using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlingar.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillåten.
        /// </summary>
        public static string allowed {
            get {
                return ResourceManager.GetString("allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numberskills.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annullera.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa användare.
        /// </summary>
        public static string Create_user {
            get {
                return ResourceManager.GetString("Create user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapad vid.
        /// </summary>
        public static string createdAt {
            get {
                return ResourceManager.GetString("createdAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synligt namn.
        /// </summary>
        public static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utvecklad av.
        /// </summary>
        public static string maintainer {
            get {
                return ResourceManager.GetString("maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillstånd.
        /// </summary>
        public static string permission {
            get {
                return ResourceManager.GetString("permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behörigheter.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga ut.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera rollbehörigheter.
        /// </summary>
        public static string Update_role_permissions {
            get {
                return ResourceManager.GetString("Update role permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera användare.
        /// </summary>
        public static string Update_user {
            get {
                return ResourceManager.GetString("Update user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera information.
        /// </summary>
        public static string updateInfo {
            get {
                return ResourceManager.GetString("updateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamn.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användare.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa behörighetssida.
        /// </summary>
        public static string View_permission_page {
            get {
                return ResourceManager.GetString("View permission page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa behörigheter.
        /// </summary>
        public static string View_permissions {
            get {
                return ResourceManager.GetString("View permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se roller.
        /// </summary>
        public static string View_roles {
            get {
                return ResourceManager.GetString("View roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa användarsidan.
        /// </summary>
        public static string View_user_page {
            get {
                return ResourceManager.GetString("View user page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa användare.
        /// </summary>
        public static string View_users {
            get {
                return ResourceManager.GetString("View users", resourceCulture);
            }
        }
    }
}
